=== alexyangfox/public-domain/moth-0.5.3/moth.dtd
<!--  moth-0-5-3.dtd  -->
<!--  $Id: moth.dtd,v 1.10 2004/03/17 04:24:08 drewfish Exp $  -->
<!--  Placed in the public domain by Drew Folta, 2002.  Share and enjoy!  -->



<!ELEMENT moth (mysql | rpn | rrd | textfile | image)* >
<!ATTLIST moth
    draw          (on | 1 | off | 0)  "on"
    dump-columns  (on | 1 | off | 0)  "off"
    draw-nan      (on | 1 | off | 0)  "off"
    profile       (on | 1 | off | 0)  "off"
    quiet         (on | 1 | off | 0)  "off"
    xml-relative  (on | 1 | off | 0)  "off"
    dump-xml      (on | 1 | off | 0)  "off"
>



<!-- ==================== DATA SOURCES ==================== -->
<!ELEMENT mysql (#PCDATA) >
<!ATTLIST mysql
    columns       CDATA       #REQUIRED
    host          CDATA       #IMPLIED
    database      CDATA       #REQUIRED
    username      CDATA       #IMPLIED
    password      CDATA       #IMPLIED
>


<!ELEMENT rpn (#PCDATA) >
<!ATTLIST rpn
    columns       CDATA       #REQUIRED
>


<!ELEMENT rrd (#PCDATA) >
<!ATTLIST rrd
    columns       CDATA       #REQUIRED
    filename      CDATA       #REQUIRED
    cf            (AVG | MIN | MAX | LAST)  #REQUIRED
    resolution    CDATA       #IMPLIED
    start         CDATA       #IMPLIED
    end           CDATA       #IMPLIED
>


<!ELEMENT textfile (EMPTY) >
<!ATTLIST textfile
    columns       CDATA   #REQUIRED
    filename      CDATA   #REQUIRED
    skip          CDATA   #IMPLIED
    delimiter     CDATA   #IMPLIED
>



<!-- ==================== IMAGE ELEMENTS ==================== -->
<!ELEMENT image (axis | area | grid | line | points | segments)* >
<!ATTLIST image
    filename      CDATA   #REQUIRED
    fileformat    CDATA   #IMPLIED
    width         CDATA   #REQUIRED
    height        CDATA   #REQUIRED
    size-type     (image | canvas)  "canvas"
    title         CDATA   #IMPLIED
    background    CDATA   #IMPLIED
    canvas        CDATA   #IMPLIED
    border-color  CDATA   #IMPLIED
    border-size   CDATA   #IMPLIED
>


<!ELEMENT axis (label)* >
<!ATTLIST axis
    location      (left | top | right | bottom)   #REQUIRED
    scaling       (linear | log2 | loge | log10 | auto)  "linear"
    clip-min      CDATA   #IMPLIED
    clip-max      CDATA   #IMPLIED
    clip-force    (on | 1 | off | 0)  "off"
    snap-to       CDATA   #IMPLIED
    title         CDATA   #IMPLIED
    color         CDATA   #IMPLIED
>


<!ELEMENT label (#PCDATA) >
<!ATTLIST label
    color         CDATA   #IMPLIED
    modulus       CDATA   #REQUIRED
    offset        CDATA   #IMPLIED
>



<!-- ==================== DRAWING LAYERS ==================== -->
<!ELEMENT area (EMPTY) >
<!ATTLIST area
    title         CDATA   #IMPLIED
    color         CDATA   #IMPLIED
    x0            CDATA   #IMPLIED
    y0            CDATA   #IMPLIED
    x1            CDATA   #IMPLIED
    y1            CDATA   #IMPLIED
    x-axis        CDATA   #IMPLIED
    y-axis        CDATA   #IMPLIED
>


<!ELEMENT grid (EMPTY) >
<!ATTLIST grid
    color         CDATA   #IMPLIED
    x-modulus     CDATA   #REQUIRED
    y-modulus     CDATA   #REQUIRED
    x-offset      CDATA   #IMPLIED
    y-offset      CDATA   #IMPLIED
    x-axis        CDATA   #IMPLIED
    y-axis        CDATA   #IMPLIED
>


<!ELEMENT line (EMPTY) >
<!ATTLIST line
    title         CDATA   #IMPLIED
    color         CDATA   #IMPLIED
    x             CDATA   #IMPLIED
    y             CDATA   #IMPLIED
    x-axis        CDATA   #IMPLIED
    y-axis        CDATA   #IMPLIED
    width         CDATA   #IMPLIED
>


<!ELEMENT points (EMPTY) >
<!ATTLIST points
    title         CDATA   #IMPLIED
    color         CDATA   #IMPLIED
    x             CDATA   #IMPLIED
    y             CDATA   #IMPLIED
    x-axis        CDATA   #IMPLIED
    y-axis        CDATA   #IMPLIED
    radius        CDATA   #IMPLIED
    filled        (on | 1 | off | 0)  "off"
>


<!ELEMENT segments (EMPTY) >
<!ATTLIST segments
    title         CDATA   #IMPLIED
    color         CDATA   #IMPLIED
    x0            CDATA   #IMPLIED
    y0            CDATA   #IMPLIED
    x1            CDATA   #IMPLIED
    y1            CDATA   #IMPLIED
    x-axis        CDATA   #IMPLIED
    y-axis        CDATA   #IMPLIED
    width         CDATA   #IMPLIED
>

=== alexyangfox/public-domain/moth-0.5.3/examples/sfo.xml
<?xml version="1.0" standalone="no" ?>
<!DOCTYPE moth SYSTEM "../moth.dtd" >

<moth xml-relative="on" >

  <textfile columns="x,temp_c" filename="sfo.data" delimiter="***" skip="1" />
  <!--
  <rrd columns="x,temp_c" filename="sfo.rrd" cf="AVERAGE" start="1024344000" end="1024444800" resolution="3600">
    temp_c
  </rrd>
  -->
  <!--
  <mysql columns="x,temp_c" database="weather">
    SELECT cycle, temperature
    FROM sfo
    ORDER BY cycle DESC
    LIMIT 30
  </mysql>
  -->

  <rpn columns="temp_f">temp_c 5 / 9 * 32 +</rpn>
  <rpn columns="avg_temp">
<!-- previous row --> ( 1 avg_temp PREV ) ( temp_f )          ( ISFIRST ) IF
<!-- this row -->     ( temp_f )          ( 1 avg_temp PREV ) ( temp_f ISNAN ) IF
<!-- next row -->     ( -1 temp_f PREV )  ( 1 avg_temp PREV ) ( -1 temp_f PREV ISNAN ) IF
<!-- average -->      + + 3 /
  </rpn>

  <image filename="sfo.png" height="200" width="600" title="temperature at SFO" >

    <axis location="left" title="degrees farenheit">
      <label modulus="10" offset="5" color="grey50">%#</label>
      <label modulus="10">%#</label>
    </axis>
    <axis location="bottom">
      <label modulus="12dH" offset="6dH" color="grey50">%dHh</label>
      <label modulus="12dH">%dHh</label>
    </axis>

    <grid color="grey80" x-modulus="12dH" y-modulus="10" />
    <line color="blue" y="avg_temp" title="average" width="0.7" />
    <area color="green#88" y0="avg_temp" y1="temp_f" />
    <!--
    <segments color="blue" y0="avg_temp" y1="temp_f" width="1.0" />
    -->
    <points color="red" y="temp_f" title="temperature" radius="3" />

  </image>
</moth>
